// Generated by js_of_ocaml
//# buildInfo:effects=false, use-js-string=false, version=5.0.1
(function
   (globalThis)
   {"use strict";
    var
     runtime=globalThis.jsoo_runtime,
     caml_string_of_jsbytes=runtime.caml_string_of_jsbytes;
    function caml_call1(f,a0)
     {return f.length == 1?f(a0):runtime.caml_call_gen(f,[a0])}
    function caml_call3(f,a0,a1,a2)
     {return f.length == 3?f(a0,a1,a2):runtime.caml_call_gen(f,[a0,a1,a2])}
    var
     global_data=runtime.caml_get_global_data(),
     cst=caml_string_of_jsbytes(""),
     Stdlib_Digest=global_data.Stdlib__Digest,
     Assert_failure=global_data.Assert_failure,
     empty=caml_call1(Stdlib_Digest[3],cst),
     _a_=[0,caml_string_of_jsbytes("md5/src/md5_lib.ml"),16,22];
    function make(s){return runtime.caml_string_equal(s,empty)?empty:s}
    var compare=runtime.caml_compare,length=16;
    function to_binary(s){return s}
    function of_binary_exn(s)
     {if(runtime.caml_ml_string_length(s) === 16)return make(s);
      throw [0,Assert_failure,_a_]}
    var to_hex=Stdlib_Digest[10];
    function of_hex_exn(s){return make(caml_call1(Stdlib_Digest[11],s))}
    function string(s){return make(caml_call1(Stdlib_Digest[3],s))}
    function bytes(s){return make(caml_call1(Stdlib_Digest[4],s))}
    function subbytes(bytes,pos,len)
     {return make(caml_call3(Stdlib_Digest[6],bytes,pos,len))}
    var
     Md5_lib=
      [0,
       compare,
       length,
       to_binary,
       of_binary_exn,
       make,
       to_hex,
       of_hex_exn,
       string,
       bytes,
       subbytes];
    runtime.caml_register_global(4,Md5_lib,"Md5_lib");
    return}
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJtZDVfbGliLmNtYS5qcyIsInNvdXJjZVJvb3QiOiIiLCJuYW1lcyI6WyJlbXB0eSIsIm1ha2UiLCJzIiwiY29tcGFyZSIsImxlbmd0aCIsInRvX2JpbmFyeSIsIm9mX2JpbmFyeV9leG4iLCJ0b19oZXgiLCJvZl9oZXhfZXhuIiwic3RyaW5nIiwiYnl0ZXMiLCJzdWJieXRlcyIsInBvcyIsImxlbiJdLCJzb3VyY2VzIjpbIi9ob21lL2Jlbi8ub3BhbS80LjE0L2xpYi9iYXNlL21kNS9tZDVfbGliLm1sIl0sIm1hcHBpbmdzIjoiOzs7OztJOzs7Ozs7O0lBR1k7Ozs7Ozs7YUFDUkMsS0FBS0MsR0FDSixpQ0FESUEsRUFETEYsYUFDS0UsQ0FJSjtJQUxPO2FBV1JHLFVBQVVILEdBQUksT0FBSkEsQ0FBSztJQVhQLFNBWVJJLGNBQWNKO01BQUksaUNBQUpBLFVBQXVDLE9BWHJERCxLQVdjQztrQ0FBNkM7SUFabkQsSUFlUks7SUFmUSxTQWdCUkMsV0FBV04sR0FBUyxPQWZwQkQsS0Flb0IsNkJBQVRDLEdBQTRCO0lBaEIvQixTQWtCUk8sT0FBT1AsR0FBUyxPQWpCaEJELEtBaUJnQiw0QkFBVEMsR0FBMEI7SUFsQnpCLFNBb0JSUSxNQUFNUixHQUFTLE9BbkJmRCxLQW1CZSw0QkFBVEMsR0FBeUI7SUFwQnZCLFNBc0JSUyxTQUFTRCxNQUFPRSxJQUFLQztNQUFXLE9BckJoQ1osS0FxQmdDLDRCQUF2QlMsTUFBT0UsSUFBS0MsS0FBMEM7SUF0QnZEOzs7T0FPUlY7T0FFQUM7T0FFQUM7T0FDQUM7T0FYQUw7T0FjQU07T0FDQUM7T0FFQUM7T0FFQUM7T0FFQUM7SUF0QlE7VSIsInNvdXJjZXNDb250ZW50IjpbInR5cGUgdCA9IHN0cmluZ1xuXG4oKiBTaGFyZSB0aGUgZGlnZXN0IG9mIHRoZSBlbXB0eSBzdHJpbmcgKilcbmxldCBlbXB0eSA9IERpZ2VzdC5zdHJpbmcgXCJcIlxubGV0IG1ha2UgcyA9XG4gIGlmIHMgPSBlbXB0eSB0aGVuXG4gICAgZW1wdHlcbiAgZWxzZVxuICAgIHNcblxubGV0IGNvbXBhcmUgPSBjb21wYXJlXG5cbmxldCBsZW5ndGggPSAxNlxuXG5sZXQgdG9fYmluYXJ5IHMgPSBzXG5sZXQgb2ZfYmluYXJ5X2V4biBzID0gYXNzZXJ0IChTdHJpbmcubGVuZ3RoIHMgPSBsZW5ndGgpOyBtYWtlIHNcbmxldCB1bnNhZmVfb2ZfYmluYXJ5ID0gbWFrZVxuXG5sZXQgdG9faGV4ID0gRGlnZXN0LnRvX2hleFxubGV0IG9mX2hleF9leG4gcyA9IG1ha2UgKERpZ2VzdC5mcm9tX2hleCBzKVxuXG5sZXQgc3RyaW5nIHMgPSBtYWtlIChEaWdlc3Quc3RyaW5nIHMpXG5cbmxldCBieXRlcyBzID0gbWFrZSAoRGlnZXN0LmJ5dGVzIHMpXG5cbmxldCBzdWJieXRlcyBieXRlcyB+cG9zIH5sZW4gPSBtYWtlIChEaWdlc3Quc3ViYnl0ZXMgYnl0ZXMgcG9zIGxlbilcbiJdfQ==
