// Generated by js_of_ocaml
//# buildInfo:effects=false, use-js-string=false, version=5.0.1
(function
   (globalThis)
   {"use strict";
    var runtime=globalThis.jsoo_runtime,Fieldslib=[0];
    runtime.caml_register_global(0,Fieldslib,"Fieldslib");
    return}
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJmaWVsZHNsaWIuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbXSwic291cmNlcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7O1UiLCJzb3VyY2VzQ29udGVudCI6W119
