// Generated by js_of_ocaml
//# buildInfo:effects=false, use-js-string=false, version=5.0.1
(function
   (globalThis)
   {"use strict";
    var runtime=globalThis.jsoo_runtime;
    function caml_call1(f,a0)
     {return f.length == 1?f(a0):runtime.caml_call_gen(f,[a0])}
    function return$0(x){return x}
    function bind(t,f){return caml_call1(f,t)}
    function to_run(t){return t}
    var IO_flush=[0,return$0,bind,to_run];
    function sanitize(s){return s}
    function run(f){return caml_call1(f,0)}
    function flushed(param){return 1}
    var Expect_test_config=[0,[0],IO_flush,run,flushed,sanitize,15023];
    runtime.caml_register_global(0,Expect_test_config,"Expect_test_config");
    return}
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJleHBlY3RfdGVzdF9jb25maWcuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbInJldHVybiQwIiwieCIsImJpbmQiLCJ0IiwiZiIsInRvX3J1biIsInNhbml0aXplIiwicyIsInJ1biIsImZsdXNoZWQiXSwic291cmNlcyI6WyIvaG9tZS9iZW4vLm9wYW0vNC4xNC9saWIvcHB4X2V4cGVjdC9jb25maWcvZXhwZWN0X3Rlc3RfY29uZmlnLm1sIl0sIm1hcHBpbmdzIjoiOzs7OztJOzs7YUFHTUEsU0FBT0MsR0FBSSxPQUFKQSxDQUFLO2FBQ1pDLEtBQUtDLEVBQUdDLEdBQUksa0JBQUpBLEVBQUhELEVBQVU7YUFNZkUsT0FBT0YsR0FBSSxPQUFKQSxDQUFLO29CQVBaSCxTQUNBRSxLQU1BRzthQUdGQyxTQUFTQyxHQUFJLE9BQUpBLENBQUs7YUFDZEMsSUFBSUosR0FBSSxrQkFBSkEsSUFBUTthQUNaSyxlQUFhLFFBQUk7MkNBRGpCRCxJQUNBQyxRQUZBSDs7VSIsInNvdXJjZXNDb250ZW50IjpbIm1vZHVsZSBJT19ydW4gPSBzdHJ1Y3RcbiAgdHlwZSAnYSB0ID0gJ2FcblxuICBsZXQgcmV0dXJuIHggPSB4XG4gIGxldCBiaW5kIHQgfmYgPSBmIHRcbmVuZFxuXG5tb2R1bGUgSU9fZmx1c2ggPSBzdHJ1Y3RcbiAgaW5jbHVkZSBJT19ydW5cblxuICBsZXQgdG9fcnVuIHQgPSB0XG5lbmRcblxubGV0IHNhbml0aXplIHMgPSBzXG5sZXQgcnVuIGYgPSBmICgpXG5sZXQgZmx1c2hlZCAoKSA9IHRydWUgKCogdGhlIHJ1bnRpbWUgZmx1c2hlZCBbc3Rkb3V0XSBiZWZvcmUgY2FsbGluZyB0aGlzIGZ1bmN0aW9uICopXG5cbmxldCB1cG9uX3VucmVsZWFzYWJsZV9pc3N1ZSA9IGBDUlxuIl19
